services:

  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - frontend
    restart: always
    environment:
      - .env

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
    networks:
      - frontend
      - backend
    restart: always
    env_file:
      - .env

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend
    restart: always
    env_file:
    - .env

volumes:

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/mariadb
      o: bind

networks:
  frontend:
  backend:
